
spring:
  datasource:
    url: jdbc:sqlite:db.sqlite
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: update  # ?? ?? ? update
    show-sql: true
    database-platform: org.hibernate.community.dialect.SQLiteDialect

  # max-file-size --> file ??? ?? ?? ??
  # max-request-size --> ?? ??? ?? ?? ??

  servlet:
    multipart:
      max-file-size: 50MB # ex) 10MB
      max-request-size: 50MB # ex) 10MB

    # ?? ?? ? ???? ???? ??
#    defer-datasource-initialization: true
#  sql:
#    init:
#      mode: always
# ?? ??? ? ??
#jwt:
#  secret: aaaabbbsdifqbvaesoioegwaaaabbbsdifqbvaesoioegwaaaabbbsdifqbvaesasdfqve